name: Release

on:
  push:
    branches: [main, develop]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [main, develop]

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest
    name: "🚀 Release // ${{ github.ref_name }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Build
        run: go build -trimpath

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: build --clean --snapshot --verbose --single-target
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
